---

- name: Temporary directory
  file:
    path: "{{ linuxbrew_install_tmp }}"
    state: directory
  become: false

- name: Download Linuxbrew install script
  get_url:
    url: "{{ linuxbrew_install_url }}"
    dest: "{{ linuxbrew_install_tmp }}/install.sh"
    checksum: "{{ linuxbrew_install_checksum }}"
    mode: 0777
  become: false

- name: Install Linuxbrew
  command: sh -c "{{ linuxbrew_install_tmp }}/install.sh"
  register: install_result
  changed_when: "install_result.rc == 0"
  become: false

- name: Remove temporary directory
  file:
    path: "{{ linuxbrew_install_tmp }}"
    state: absent
  become: false
