---

- name: Set path to Linuxbrew prefix
  set_fact:
    linuxbrew_prefix: "{{ item }}"
  with_first_found:
    - "{{ linuxbrew_prefix_shared }}"
    - "{{ linuxbrew_prefix_user }}"
  become: true

- name: Load Linuxbrew in bash
  include_tasks: shell_bash.yml
  when: linuxbrew_prefix is defined

- name: Load Linuxbrew in zsh
  include_tasks: shell_zsh.yml
  when: linuxbrew_prefix is defined
